services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data:/opt/couchdb/data

  backend:
    build: ./Server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - COUCHDB_URL=http://admin:admin@couchdb:5984
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - USE_CACHE=false
    depends_on:
      - couchdb
      - elasticsearch
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./Front
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  populate-db:
    build:
      context: ./Server
    container_name: populate-db
    entrypoint: ["node", "scripts/populateDatabase.js"]
    depends_on:
      - couchdb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  couchdb_data:
  elasticsearch_data:
